# Generated by Django 5.0.6 on 2024-05-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extracteddata',
            old_name='paragraphs',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='tables',
        ),
    ]
